// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// IdentityUIClient is the client API for IdentityUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IdentityUIClient interface {
	// ListEngineSpecs returns a list of Identity Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (IdentityUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type identityUIClient struct {
	cc grpc.ClientConnInterface
}

func NewIdentityUIClient(cc grpc.ClientConnInterface) IdentityUIClient {
	return &identityUIClient{cc}
}

func (c *identityUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (IdentityUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &IdentityUI_ServiceDesc.Streams[0], "/v1.IdentityUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &identityUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type IdentityUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type identityUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *identityUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *identityUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.IdentityUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentityUIServer is the server API for IdentityUI service.
// All implementations must embed UnimplementedIdentityUIServer
// for forward compatibility
type IdentityUIServer interface {
	// ListEngineSpecs returns a list of Identity Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, IdentityUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedIdentityUIServer()
}

// UnimplementedIdentityUIServer must be embedded to have forward compatible implementations.
type UnimplementedIdentityUIServer struct {
}

func (UnimplementedIdentityUIServer) ListEngineSpecs(*ListEngineSpecsRequest, IdentityUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedIdentityUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedIdentityUIServer) mustEmbedUnimplementedIdentityUIServer() {}

// UnsafeIdentityUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdentityUIServer will
// result in compilation errors.
type UnsafeIdentityUIServer interface {
	mustEmbedUnimplementedIdentityUIServer()
}

func RegisterIdentityUIServer(s grpc.ServiceRegistrar, srv IdentityUIServer) {
	s.RegisterService(&IdentityUI_ServiceDesc, srv)
}

func _IdentityUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(IdentityUIServer).ListEngineSpecs(m, &identityUIListEngineSpecsServer{stream})
}

type IdentityUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type identityUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *identityUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _IdentityUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.IdentityUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IdentityUI_ServiceDesc is the grpc.ServiceDesc for IdentityUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IdentityUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.IdentityUI",
	HandlerType: (*IdentityUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _IdentityUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _IdentityUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "identity-ui.proto",
}
